import MidenLean.Symbolic.Exec

/-!
# Per-instruction soundness helpers

Helper theorems for `execInstruction_sound` proving that each supported instruction's
symbolic execution is sound with respect to concrete execution.

Organized in three parts:
- **Shared helpers**: list and precondition lemmas used across proofs
- **Generated lemmas**: stack-only instructions, emitted by the `sound_stack_op`
  command from the operand count, the instruction and its concrete handler
- **Hand-written lemmas**: everything whose proof does not fit that template
  (indexed and word-wide stack access, static immediate bounds, conditional
  data flow, and the state-preserving `u32Assert*` family)
-/

namespace MidenLean.Symbolic

-- Shared helper lemmas

/-- File-local convenience wrapper around Mathlib's
    `List.getElem?_eq_some_iff` (use that lemma directly outside this file). -/
private theorem getElem?_some_lt {α : Type} (l : List α) (n : Nat) (v : α)
    (h : l[n]? = some v) : n < l.length :=
  List.getElem?_eq_some_iff.mp h |>.1

/-- File-local convenience wrapper around Mathlib's
    `List.getElem?_eq_some_iff` (use that lemma directly outside this file). -/
private theorem getElem_of_getElem?_some {α : Type} (l : List α) (n : Nat) (v : α)
    (h : l[n]? = some v) : l[n]'(getElem?_some_lt l n v h) = v := by
  have := List.getElem?_eq_getElem (getElem?_some_lt l n v h) (α := α)
  rw [this] at h; exact Option.some.inj h

theorem getElem?_map_append_left {α β : Type} (f : α → β)
    (l : List α) (rest : List β) (n : Nat) (hn : n < l.length) :
    (l.map f ++ rest)[n]? = some (f l[n]) := by
  rw [List.getElem?_append, if_pos (by simp; omega), List.getElem?_map,
      List.getElem?_eq_getElem (by omega)]
  rfl

theorem set_map_append_left {α β : Type} (f : α → β)
    (l : List α) (rest : List β) (n : Nat) (x : α) (hn : n < l.length) :
    (l.set n x).map f ++ rest = (l.map f ++ rest).set n (f x) := by
  rw [List.map_set, List.set_append, if_pos (by simp; omega)]

theorem eraseIdx_map_append_left {α β : Type} (f : α → β)
    (l : List α) (rest : List β) (n : Nat) (hn : n < l.length) :
    (l.map f ++ rest).eraseIdx n = (l.eraseIdx n).map f ++ rest := by
  rw [List.eraseIdx_append_of_lt_length (by simp; omega), List.eraseIdx_map]

theorem isBool_guard (x : Felt) (h : x = 0 ∨ x = 1) : x.isBool = true := by
  unfold Felt.isBool
  rcases h with rfl | rfl <;> decide

theorem map_lit_map_eval (σ : Assignment) (vs : List Felt) :
    (vs.map Expr.lit).map (Expr.eval σ) = vs := by
  induction vs with
  | nil => rfl
  | cons v rest ih => simp [Expr.eval, ih]

-- Helper: a = b → (a == b) = true for Felt
theorem feltEq_beq_guard (a b : Felt) (h : a = b) : ((a == b) = true) := by
  subst h
  simp

/-- Convert the symbolic `.nonzero` precondition (Felt BEq with 0 is false)
    to a Nat-level `val == 0 = false` fact usable in concrete guards. -/
theorem felt_nonzero_val_ne_zero {x : Felt}
    (h : ((x == (0 : Felt)) = false)) : ((x.val == 0) = false) := by
  simp only [beq_eq_false_iff_ne, ne_eq] at h ⊢
  intro hval
  apply h
  exact (ZMod.val_eq_zero x).mp hval

/-- For small n (n ≤ 31), (Felt.ofNat n).val = n. Used in Imm instruction proofs
    to bridge symbolic evaluation (which goes through .lit (Felt.ofNat n)) and
    concrete execution (which uses n directly). -/
theorem feltOfNat_val_small (n : Nat) (hn : n ≤ 31) :
    (Felt.ofNat n).val = n := by
  unfold Felt.ofNat
  simp only [Felt, GOLDILOCKS_PRIME]
  rw [ZMod.val_natCast]
  apply Nat.mod_eq_of_lt
  omega

/-! ## Generated per-instruction lemmas

Most supported instructions are *stack-only*: they pop a fixed number of
operands, push a symbolic result, and leave memory, frames and advice
untouched. All of those share a single proof, so they are generated by the
`sound_stack_op` command below instead of being spelled out one by one.

    sound_stack_op <operands popped> <name suffix> <instruction> <handler>
      [<handler arguments>] (using [<extra simp lemmas>])? (with <extra binders>)?

For example `sound_stack_op 2 lt .lt execLt` generates
`execInstruction_sound_lt`, and `sound_stack_op 1 divImm (.divImm v) execDivImm v
with (v : Felt)` generates `execInstruction_sound_divImm`. Statements are
identical to the hand-written ones (same name, same binder order), so
`Soundness.lean`'s dispatcher calls them positionally as before.

The four `macro_rules` differ only in the stack pattern they match — one per
supported operand count. Instructions needing a different proof shape (indexed
stack access, static immediate bounds, conditional data flow, or the
state-preserving `u32Assert*` family) are written out by hand below.
-/

/-- The shared soundness step for stack-only instructions: given that the
    symbolic step only rewrote the stack to `stk`, the concrete successor is
    `cs.withStack (stk.map (Expr.eval σ) ++ rest)`, and every non-stack
    component of `models` is inherited from `hmodels`. -/
theorem sound_withStack {i : Instruction} {ss : State} {stk : List Expr}
    {cs : Concrete.State} {σ : Assignment} {rest : List Felt}
    (hmodels : ss.models cs σ rest)
    (hc : MidenLean.execInstruction cs i
        = some (cs.withStack (stk.map (Expr.eval σ) ++ rest))) :
    ∃ cs', MidenLean.execInstruction cs i = some cs' ∧
      ({ ss with stack := stk } : State).models cs' σ rest := by
  obtain ⟨_, hmem, hframes, hadv⟩ := hmodels
  exact ⟨_, hc, rfl, hmem, hframes, hadv⟩

/-- Bridge a `.valLeq` precondition to the `>` guard of a concrete handler.
    Stated as a `= False` rewrite so `simp` can discharge the guard. -/
theorem lt_val_eq_false_of_le {x : Felt} {n : Nat} (h : x.val ≤ n) :
    (n < x.val) = False := by simp; omega

open Lean Parser.Tactic in
/-- See the section comment above. -/
local syntax "sound_stack_op " num ident term:max ident (ppSpace term:max)*
    (" using " "[" simpLemma,* "]")? (" with " bracketedBinder+)? : command

-- The three `try` steps cover the optional parts of the template: instructions
-- without preconditions have nothing to normalise in `hpreconds`, `simp` closes
-- most concrete goals outright, and the trailing `rfl` absorbs handlers written
-- with a definitionally equal operation (`&&&` versus `Nat.land`, say). A step
-- that genuinely fails leaves its goal open, so the theorem still fails loudly.
macro_rules
  | `(sound_stack_op 1 $suffix:ident $instr:term $ec:ident $args:term*
        $[using [$extras,*]]? $[with $binders*]?) => do
    let name := Lean.mkIdentFrom suffix
      (Lean.Name.mkSimple ("execInstruction_sound_" ++ suffix.getId.toString))
    let extras := extras.getD ⟨#[]⟩
    let binders := binders.getD #[]
    `(theorem $name $binders* (ss : State) (cs : Concrete.State)
          (σ : Assignment) (rest : List Felt)
          (ss' : State) (preconds : List Precondition)
          (hmodels : ss.models cs σ rest)
          (hexec : execInstruction ss $instr = some (ss', preconds))
          (hpreconds : ∀ p ∈ preconds, p.holds σ) :
          ∃ cs', MidenLean.execInstruction cs $instr = some cs' ∧
            ss'.models cs' σ rest := by
        simp only [execInstruction] at hexec
        match hstk : ss.stack with
        | [] => simp [hstk] at hexec
        | e₁ :: tail =>
          simp only [hstk] at hexec
          obtain ⟨hss, hpre⟩ := Prod.mk.inj (Option.some.inj hexec)
          subst hss
          subst hpre
          refine sound_withStack hmodels ?_
          obtain ⟨hstack, -, -, -⟩ := hmodels
          rw [hstk] at hstack
          try simp only [List.forall_mem_cons, List.not_mem_nil, false_implies,
            implies_true, and_true, Precondition.holds, Expr.eval] at hpreconds
          change $ec $args* cs = _
          unfold $ec
          rw [hstack]
          try simp [*, Concrete.State.withStack, Expr.eval, isBool_guard,
            felt_nonzero_val_ne_zero, lt_val_eq_false_of_le, ZMod.val_zero,
            ZMod.val_one, $extras,*]
          try rfl)
  | `(sound_stack_op 2 $suffix:ident $instr:term $ec:ident $args:term*
        $[using [$extras,*]]? $[with $binders*]?) => do
    let name := Lean.mkIdentFrom suffix
      (Lean.Name.mkSimple ("execInstruction_sound_" ++ suffix.getId.toString))
    let extras := extras.getD ⟨#[]⟩
    let binders := binders.getD #[]
    `(theorem $name $binders* (ss : State) (cs : Concrete.State)
          (σ : Assignment) (rest : List Felt)
          (ss' : State) (preconds : List Precondition)
          (hmodels : ss.models cs σ rest)
          (hexec : execInstruction ss $instr = some (ss', preconds))
          (hpreconds : ∀ p ∈ preconds, p.holds σ) :
          ∃ cs', MidenLean.execInstruction cs $instr = some cs' ∧
            ss'.models cs' σ rest := by
        simp only [execInstruction] at hexec
        match hstk : ss.stack with
        | [] | [_] => simp [hstk] at hexec
        | e₁ :: e₂ :: tail =>
          simp only [hstk] at hexec
          obtain ⟨hss, hpre⟩ := Prod.mk.inj (Option.some.inj hexec)
          subst hss
          subst hpre
          refine sound_withStack hmodels ?_
          obtain ⟨hstack, -, -, -⟩ := hmodels
          rw [hstk] at hstack
          try simp only [List.forall_mem_cons, List.not_mem_nil, false_implies,
            implies_true, and_true, Precondition.holds, Expr.eval] at hpreconds
          change $ec $args* cs = _
          unfold $ec
          rw [hstack]
          try simp [*, Concrete.State.withStack, Expr.eval, isBool_guard,
            felt_nonzero_val_ne_zero, lt_val_eq_false_of_le, ZMod.val_zero,
            ZMod.val_one, $extras,*]
          try rfl)
  | `(sound_stack_op 3 $suffix:ident $instr:term $ec:ident $args:term*
        $[using [$extras,*]]? $[with $binders*]?) => do
    let name := Lean.mkIdentFrom suffix
      (Lean.Name.mkSimple ("execInstruction_sound_" ++ suffix.getId.toString))
    let extras := extras.getD ⟨#[]⟩
    let binders := binders.getD #[]
    `(theorem $name $binders* (ss : State) (cs : Concrete.State)
          (σ : Assignment) (rest : List Felt)
          (ss' : State) (preconds : List Precondition)
          (hmodels : ss.models cs σ rest)
          (hexec : execInstruction ss $instr = some (ss', preconds))
          (hpreconds : ∀ p ∈ preconds, p.holds σ) :
          ∃ cs', MidenLean.execInstruction cs $instr = some cs' ∧
            ss'.models cs' σ rest := by
        simp only [execInstruction] at hexec
        match hstk : ss.stack with
        | [] | [_] | [_, _] => simp [hstk] at hexec
        | e₁ :: e₂ :: e₃ :: tail =>
          simp only [hstk] at hexec
          obtain ⟨hss, hpre⟩ := Prod.mk.inj (Option.some.inj hexec)
          subst hss
          subst hpre
          refine sound_withStack hmodels ?_
          obtain ⟨hstack, -, -, -⟩ := hmodels
          rw [hstk] at hstack
          try simp only [List.forall_mem_cons, List.not_mem_nil, false_implies,
            implies_true, and_true, Precondition.holds, Expr.eval] at hpreconds
          change $ec $args* cs = _
          unfold $ec
          rw [hstack]
          try simp [*, Concrete.State.withStack, Expr.eval, isBool_guard,
            felt_nonzero_val_ne_zero, lt_val_eq_false_of_le, ZMod.val_zero,
            ZMod.val_one, $extras,*]
          try rfl)
  | `(sound_stack_op 4 $suffix:ident $instr:term $ec:ident $args:term*
        $[using [$extras,*]]? $[with $binders*]?) => do
    let name := Lean.mkIdentFrom suffix
      (Lean.Name.mkSimple ("execInstruction_sound_" ++ suffix.getId.toString))
    let extras := extras.getD ⟨#[]⟩
    let binders := binders.getD #[]
    `(theorem $name $binders* (ss : State) (cs : Concrete.State)
          (σ : Assignment) (rest : List Felt)
          (ss' : State) (preconds : List Precondition)
          (hmodels : ss.models cs σ rest)
          (hexec : execInstruction ss $instr = some (ss', preconds))
          (hpreconds : ∀ p ∈ preconds, p.holds σ) :
          ∃ cs', MidenLean.execInstruction cs $instr = some cs' ∧
            ss'.models cs' σ rest := by
        simp only [execInstruction] at hexec
        match hstk : ss.stack with
        | [] | [_] | [_, _] | [_, _, _] => simp [hstk] at hexec
        | e₁ :: e₂ :: e₃ :: e₄ :: tail =>
          simp only [hstk] at hexec
          obtain ⟨hss, hpre⟩ := Prod.mk.inj (Option.some.inj hexec)
          subst hss
          subst hpre
          refine sound_withStack hmodels ?_
          obtain ⟨hstack, -, -, -⟩ := hmodels
          rw [hstk] at hstack
          try simp only [List.forall_mem_cons, List.not_mem_nil, false_implies,
            implies_true, and_true, Precondition.holds, Expr.eval] at hpreconds
          change $ec $args* cs = _
          unfold $ec
          rw [hstack]
          try simp [*, Concrete.State.withStack, Expr.eval, isBool_guard,
            felt_nonzero_val_ne_zero, lt_val_eq_false_of_le, ZMod.val_zero,
            ZMod.val_one, $extras,*]
          try rfl)


-- Field arithmetic (single operand)
sound_stack_op 1 neg .neg execNeg
sound_stack_op 1 incr .incr execIncr
sound_stack_op 1 inv .inv execInv
sound_stack_op 1 pow2 .pow2 execPow2
sound_stack_op 1 isOdd .isOdd execIsOdd
sound_stack_op 1 not .not execNot

-- Field arithmetic and comparison with an immediate
sound_stack_op 1 addImm (.addImm v) execAddImm v with (v : Felt)
sound_stack_op 1 subImm (.subImm v) execSubImm v with (v : Felt)
sound_stack_op 1 mulImm (.mulImm v) execMulImm v with (v : Felt)
sound_stack_op 1 divImm (.divImm v) execDivImm v with (v : Felt)
sound_stack_op 1 eqImm (.eqImm v) execEqImm v with (v : Felt)
sound_stack_op 1 neqImm (.neqImm v) execNeqImm v with (v : Felt)

-- Field comparison and boolean (two operands)
sound_stack_op 2 neq .neq execNeq
sound_stack_op 2 lt .lt execLt
sound_stack_op 2 lte .lte execLte
sound_stack_op 2 gt .gt execGt
sound_stack_op 2 gte .gte execGte
sound_stack_op 2 or .or execOr
sound_stack_op 2 xor .xor execXor
sound_stack_op 2 div .div execDiv

-- Assertions
sound_stack_op 1 assert .assert execAssert
sound_stack_op 1 assertWithError (.assertWithError msg) execAssert with (msg : String)
sound_stack_op 1 assertz .assertz execAssertz
sound_stack_op 1 assertzWithError (.assertzWithError msg) execAssertz with (msg : String)
sound_stack_op 2 assertEq .assertEq execAssertEq
sound_stack_op 2 assertEqWithError (.assertEqWithError msg) execAssertEq with (msg : String)

-- U32 conversion and tests
sound_stack_op 1 u32Cast .u32Cast execU32Cast
sound_stack_op 1 u32Split .u32Split execU32Split
sound_stack_op 1 u32Test .u32Test execU32Test
sound_stack_op 4 u32TestW .u32TestW execU32TestW

-- U32 arithmetic
sound_stack_op 2 u32OverflowAdd .u32OverflowAdd execU32OverflowAdd using [u32WideAdd]
sound_stack_op 2 u32WrappingAdd .u32WrappingAdd execU32WrappingAdd using [u32WAdd, u32Max]
sound_stack_op 3 u32OverflowAdd3 .u32OverflowAdd3 execU32OverflowAdd3 using [u32WideAdd3]
sound_stack_op 3 u32WrappingAdd3 .u32WrappingAdd3 execU32WrappingAdd3 using [u32Max]
sound_stack_op 2 u32WrappingSub .u32WrappingSub execU32WrappingSub
sound_stack_op 2 u32WidenMul .u32WidenMul execU32WidenMul using [u32WideMul]
sound_stack_op 2 u32WrappingMul .u32WrappingMul execU32WrappingMul using [u32Max]
sound_stack_op 3 u32WidenMadd .u32WidenMadd execU32WidenMadd using [u32WideMadd]
sound_stack_op 3 u32WrappingMadd .u32WrappingMadd execU32WrappingMadd using [u32Max]
sound_stack_op 2 u32DivMod .u32DivMod execU32DivMod
sound_stack_op 2 u32Div .u32Div execU32Div
sound_stack_op 2 u32Mod .u32Mod execU32Mod

-- U32 bitwise and unary
sound_stack_op 2 u32And .u32And execU32And
sound_stack_op 2 u32Or .u32Or execU32Or
sound_stack_op 2 u32Xor .u32Xor execU32Xor
sound_stack_op 1 u32Not .u32Not execU32Not
sound_stack_op 1 u32Popcnt .u32Popcnt execU32Popcnt
sound_stack_op 1 u32Clz .u32Clz execU32Clz
sound_stack_op 1 u32Ctz .u32Ctz execU32Ctz
sound_stack_op 1 u32Clo .u32Clo execU32Clo
sound_stack_op 1 u32Cto .u32Cto execU32Cto

-- U32 shift and rotate
sound_stack_op 2 u32Shl .u32Shl execU32Shl
sound_stack_op 2 u32Shr .u32Shr execU32Shr
sound_stack_op 2 u32Rotl .u32Rotl execU32Rotl
sound_stack_op 2 u32Rotr .u32Rotr execU32Rotr

-- U32 comparison
sound_stack_op 2 u32Lt .u32Lt execU32Lt
sound_stack_op 2 u32Lte .u32Lte execU32Lte
sound_stack_op 2 u32Gt .u32Gt execU32Gt
sound_stack_op 2 u32Gte .u32Gte execU32Gte
sound_stack_op 2 u32Min .u32Min execU32Min
sound_stack_op 2 u32Max .u32Max execU32Max

-- Word-level stack shuffling
sound_stack_op 4 dropw .dropw execDropw
sound_stack_op 4 reversew .reversew execReversew

/-! ## Hand-written per-instruction lemmas

Instructions whose proof does not fit `sound_stack_op`: indexed or word-wide
stack access, static immediate bounds, conditional data flow, and the
state-preserving `u32Assert*` family.
-/

theorem execInstruction_sound_nop
    (ss : State) (cs : Concrete.State)
    (σ : Assignment) (rest : List Felt)
    (ss' : State) (preconds : List Precondition)
    (hmodels : ss.models cs σ rest)
    (hexec : execInstruction ss .nop = some (ss', preconds))
    (hpreconds : ∀ p ∈ preconds, p.holds σ) :
    ∃ cs', MidenLean.execInstruction cs .nop = some cs' ∧ ss'.models cs' σ rest := by
  obtain ⟨hstack, hmem, hframes, hadv⟩ := hmodels
  simp only [execInstruction] at hexec
  obtain ⟨rfl, rfl⟩ := Prod.mk.inj (Option.some.inj hexec)
  exact ⟨cs,
    by simp only [MidenLean.execInstruction],
    hstack, hmem, hframes, hadv⟩


theorem execInstruction_sound_padw
    (ss : State) (cs : Concrete.State)
    (σ : Assignment) (rest : List Felt)
    (ss' : State) (preconds : List Precondition)
    (hmodels : ss.models cs σ rest)
    (hexec : execInstruction ss .padw = some (ss', preconds))
    (hpreconds : ∀ p ∈ preconds, p.holds σ) :
    ∃ cs', MidenLean.execInstruction cs .padw = some cs' ∧ ss'.models cs' σ rest := by
  obtain ⟨hstack, hmem, hframes, hadv⟩ := hmodels
  simp only [execInstruction] at hexec
  obtain ⟨rfl, rfl⟩ := Prod.mk.inj (Option.some.inj hexec)
  exact ⟨cs.withStack (0 :: 0 :: 0 :: 0 :: cs.stack),
    by simp only [MidenLean.execInstruction, execPadw, hstack, Concrete.State.withStack],
    ⟨by simp only [Concrete.State.withStack, List.map_cons, Expr.eval, hstack,
         List.cons_append], hmem, hframes, hadv⟩⟩


theorem execInstruction_sound_push
    (v : Felt) (ss : State) (cs : Concrete.State)
    (σ : Assignment) (rest : List Felt)
    (ss' : State) (preconds : List Precondition)
    (hmodels : ss.models cs σ rest)
    (hexec : execInstruction ss (.push v) = some (ss', preconds))
    (hpreconds : ∀ p ∈ preconds, p.holds σ) :
    ∃ cs', MidenLean.execInstruction cs (.push v) = some cs' ∧ ss'.models cs' σ rest := by
  obtain ⟨hstack, hmem, hframes, hadv⟩ := hmodels
  simp only [execInstruction] at hexec
  obtain ⟨rfl, rfl⟩ := Prod.mk.inj (Option.some.inj hexec)
  exact ⟨cs.withStack (v :: cs.stack),
    by simp only [MidenLean.execInstruction, execPush, hstack, Concrete.State.withStack],
    ⟨by simp only [Concrete.State.withStack, List.map_cons, Expr.eval, hstack,
         List.cons_append], hmem, hframes, hadv⟩⟩


theorem execInstruction_sound_pushList
    (vs : List Felt) (ss : State) (cs : Concrete.State)
    (σ : Assignment) (rest : List Felt)
    (ss' : State) (preconds : List Precondition)
    (hmodels : ss.models cs σ rest)
    (hexec : execInstruction ss (.pushList vs) = some (ss', preconds))
    (hpreconds : ∀ p ∈ preconds, p.holds σ) :
    ∃ cs', MidenLean.execInstruction cs (.pushList vs) = some cs' ∧ ss'.models cs' σ rest := by
  obtain ⟨hstack, hmem, hframes, hadv⟩ := hmodels
  simp only [execInstruction] at hexec
  obtain ⟨rfl, rfl⟩ := Prod.mk.inj (Option.some.inj hexec)
  exact ⟨cs.withStack (vs ++ cs.stack),
    by simp only [MidenLean.execInstruction, execPushList, hstack, Concrete.State.withStack],
    ⟨by simp only [Concrete.State.withStack, List.map_append, hstack, List.append_assoc]; congr 1; exact (map_lit_map_eval σ vs).symm, hmem, hframes, hadv⟩⟩


theorem execInstruction_sound_swapdw
    (ss : State) (cs : Concrete.State)
    (σ : Assignment) (rest : List Felt)
    (ss' : State) (preconds : List Precondition)
    (hmodels : ss.models cs σ rest)
    (hexec : execInstruction ss .swapdw = some (ss', preconds))
    (hpreconds : ∀ p ∈ preconds, p.holds σ) :
    ∃ cs', MidenLean.execInstruction cs .swapdw = some cs' ∧ ss'.models cs' σ rest := by
  obtain ⟨hstack, hmem, hframes, hadv⟩ := hmodels
  simp only [execInstruction] at hexec
  match hstk : ss.stack with
  | a0::a1::a2::a3::b0::b1::b2::b3::c0::c1::c2::c3::d0::d1::d2::d3::tail =>
    simp only [hstk] at hexec
    obtain ⟨rfl, rfl⟩ := Prod.mk.inj (Option.some.inj hexec)
    rw [hstk] at hstack
    simp only [List.map_cons, List.cons_append] at hstack
    exact ⟨cs.withStack (c0.eval σ::c1.eval σ::c2.eval σ::c3.eval σ::
                        d0.eval σ::d1.eval σ::d2.eval σ::d3.eval σ::
                        a0.eval σ::a1.eval σ::a2.eval σ::a3.eval σ::
                        b0.eval σ::b1.eval σ::b2.eval σ::b3.eval σ::
                        tail.map (Expr.eval σ) ++ rest),
      by simp only [MidenLean.execInstruction, execSwapdw, hstack, Concrete.State.withStack]; rfl,
      ⟨by simp only [Concrete.State.withStack, List.map_cons], hmem, hframes, hadv⟩⟩
  | _ =>
    split at hexec
    · -- overlap: the 16+ element pattern matched both arms; proceed like the main case
      rename_i a0 a1 a2 a3 b0 b1 b2 b3 c0 c1 c2 c3 d0 d1 d2 d3 tail heq_stk
      obtain ⟨rfl, rfl⟩ := Prod.mk.inj (Option.some.inj hexec)
      rw [heq_stk] at hstack
      simp only [List.map_cons, List.cons_append] at hstack
      exact ⟨cs.withStack (c0.eval σ::c1.eval σ::c2.eval σ::c3.eval σ::
                            d0.eval σ::d1.eval σ::d2.eval σ::d3.eval σ::
                            a0.eval σ::a1.eval σ::a2.eval σ::a3.eval σ::
                            b0.eval σ::b1.eval σ::b2.eval σ::b3.eval σ::
                            tail.map (Expr.eval σ) ++ rest),
        by simp only [MidenLean.execInstruction, execSwapdw, hstack, Concrete.State.withStack]; rfl,
        ⟨by simp only [Concrete.State.withStack, List.map_cons], hmem, hframes, hadv⟩⟩
    · simp at hexec

theorem execInstruction_sound_eqw
    (ss : State) (cs : Concrete.State)
    (σ : Assignment) (rest : List Felt)
    (ss' : State) (preconds : List Precondition)
    (hmodels : ss.models cs σ rest)
    (hexec : execInstruction ss .eqw = some (ss', preconds))
    (hpreconds : ∀ p ∈ preconds, p.holds σ) :
    ∃ cs', MidenLean.execInstruction cs .eqw = some cs' ∧ ss'.models cs' σ rest := by
  obtain ⟨hstack, hmem, hframes, hadv⟩ := hmodels
  simp only [execInstruction] at hexec
  match hstk : ss.stack with
  | [] | [_] | [_, _] | [_, _, _] | [_, _, _, _]
  | [_, _, _, _, _] | [_, _, _, _, _, _] | [_, _, _, _, _, _, _] =>
    simp [hstk] at hexec
  | b0 :: b1 :: b2 :: b3 :: a0 :: a1 :: a2 :: a3 :: tail =>
    simp only [hstk] at hexec
    obtain ⟨rfl, rfl⟩ := Prod.mk.inj (Option.some.inj hexec)
    rw [hstk, List.map_cons, List.map_cons, List.map_cons, List.map_cons,
        List.map_cons, List.map_cons, List.map_cons, List.map_cons] at hstack
    refine ⟨cs.withStack ((if a0.eval σ == b0.eval σ && a1.eval σ == b1.eval σ &&
                               a2.eval σ == b2.eval σ && a3.eval σ == b3.eval σ
                           then (1 : Felt) else 0)
                           :: b0.eval σ :: b1.eval σ :: b2.eval σ :: b3.eval σ
                           :: a0.eval σ :: a1.eval σ :: a2.eval σ :: a3.eval σ
                           :: tail.map (Expr.eval σ) ++ rest), ?_, ?_⟩
    · change execEqw cs = _
      unfold execEqw
      rw [hstack]; simp [Concrete.State.withStack]
    · exact ⟨by simp only [Concrete.State.withStack, List.map_cons, Expr.eval,
          List.cons_append], hmem, hframes, hadv⟩


-- Assertion ops (state-preserving, precondition-guarded assertions)

theorem execInstruction_sound_assertEqw
    (ss : State) (cs : Concrete.State)
    (σ : Assignment) (rest : List Felt)
    (ss' : State) (preconds : List Precondition)
    (hmodels : ss.models cs σ rest)
    (hexec : execInstruction ss .assertEqw = some (ss', preconds))
    (hpreconds : ∀ p ∈ preconds, p.holds σ) :
    ∃ cs', MidenLean.execInstruction cs .assertEqw = some cs' ∧ ss'.models cs' σ rest := by
  obtain ⟨hstack, hmem, hframes, hadv⟩ := hmodels
  simp only [execInstruction] at hexec
  match hstk : ss.stack with
  | [] | [_] | [_, _] | [_, _, _] | [_, _, _, _]
  | [_, _, _, _, _] | [_, _, _, _, _, _] | [_, _, _, _, _, _, _] =>
    simp [hstk] at hexec
  | b0 :: b1 :: b2 :: b3 :: a0 :: a1 :: a2 :: a3 :: tail =>
    simp only [hstk] at hexec
    obtain ⟨rfl, rfl⟩ := Prod.mk.inj (Option.some.inj hexec)
    rw [hstk, List.map_cons, List.map_cons, List.map_cons, List.map_cons,
        List.map_cons, List.map_cons, List.map_cons, List.map_cons] at hstack
    have h0 : (a0.eval σ) = (b0.eval σ) :=
      hpreconds (.feltEq a0 b0) (by simp)
    have h1 : (a1.eval σ) = (b1.eval σ) :=
      hpreconds (.feltEq a1 b1) (by simp)
    have h2 : (a2.eval σ) = (b2.eval σ) :=
      hpreconds (.feltEq a2 b2) (by simp)
    have h3 : (a3.eval σ) = (b3.eval σ) :=
      hpreconds (.feltEq a3 b3) (by simp)
    have hg0 : (a0.eval σ == b0.eval σ) = true := feltEq_beq_guard _ _ h0
    have hg1 : (a1.eval σ == b1.eval σ) = true := feltEq_beq_guard _ _ h1
    have hg2 : (a2.eval σ == b2.eval σ) = true := feltEq_beq_guard _ _ h2
    have hg3 : (a3.eval σ == b3.eval σ) = true := feltEq_beq_guard _ _ h3
    have hguard : (a0.eval σ == b0.eval σ && (a1.eval σ == b1.eval σ) &&
                   (a2.eval σ == b2.eval σ) && (a3.eval σ == b3.eval σ)) = true := by
      rw [hg0, hg1, hg2, hg3]; rfl
    refine ⟨cs.withStack (tail.map (Expr.eval σ) ++ rest), ?_, ?_⟩
    · change execAssertEqw cs = _
      unfold execAssertEqw
      rw [hstack]; simp [hguard, Concrete.State.withStack]
    · exact ⟨by simp only [Concrete.State.withStack], hmem, hframes, hadv⟩


theorem execInstruction_sound_u32Assert
    (ss : State) (cs : Concrete.State)
    (σ : Assignment) (rest : List Felt)
    (ss' : State) (preconds : List Precondition)
    (hmodels : ss.models cs σ rest)
    (hexec : execInstruction ss .u32Assert = some (ss', preconds))
    (hpreconds : ∀ p ∈ preconds, p.holds σ) :
    ∃ cs', MidenLean.execInstruction cs .u32Assert = some cs' ∧ ss'.models cs' σ rest := by
  obtain ⟨hstack, hmem, hframes, hadv⟩ := hmodels
  simp only [execInstruction] at hexec
  match hstk : ss.stack with
  | [] => simp [hstk] at hexec
  | a :: tail =>
    simp only [hstk] at hexec
    obtain ⟨rfl, rfl⟩ := Prod.mk.inj (Option.some.inj hexec)
    rw [hstk, List.map_cons] at hstack
    have ha : (a.eval σ).isU32 = true :=
      hpreconds (.isU32 a) (by simp)
    refine ⟨cs, ?_, ?_⟩
    · change execU32Assert cs = _
      unfold execU32Assert
      rw [hstack]; simp [ha]
    · exact ⟨by simp only [hstk, hstack, List.map_cons], hmem, hframes, hadv⟩


theorem execInstruction_sound_u32Assert2
    (ss : State) (cs : Concrete.State)
    (σ : Assignment) (rest : List Felt)
    (ss' : State) (preconds : List Precondition)
    (hmodels : ss.models cs σ rest)
    (hexec : execInstruction ss .u32Assert2 = some (ss', preconds))
    (hpreconds : ∀ p ∈ preconds, p.holds σ) :
    ∃ cs', MidenLean.execInstruction cs .u32Assert2 = some cs' ∧ ss'.models cs' σ rest := by
  obtain ⟨hstack, hmem, hframes, hadv⟩ := hmodels
  simp only [execInstruction] at hexec
  match hstk : ss.stack with
  | [] | [_] => simp [hstk] at hexec
  | b :: a :: tail =>
    simp only [hstk] at hexec
    obtain ⟨rfl, rfl⟩ := Prod.mk.inj (Option.some.inj hexec)
    rw [hstk, List.map_cons, List.map_cons] at hstack
    have ha : (a.eval σ).isU32 = true :=
      hpreconds (.isU32 a) (by simp)
    have hb : (b.eval σ).isU32 = true :=
      hpreconds (.isU32 b) (by simp)
    have hguard : ((a.eval σ).isU32 && (b.eval σ).isU32) = true := by rw [ha, hb]; rfl
    refine ⟨cs, ?_, ?_⟩
    · change execU32Assert2 cs = _
      unfold execU32Assert2
      rw [hstack]; simp [hguard]
    · exact ⟨by simp only [hstk, hstack, List.map_cons], hmem, hframes, hadv⟩


theorem execInstruction_sound_u32AssertW
    (ss : State) (cs : Concrete.State)
    (σ : Assignment) (rest : List Felt)
    (ss' : State) (preconds : List Precondition)
    (hmodels : ss.models cs σ rest)
    (hexec : execInstruction ss .u32AssertW = some (ss', preconds))
    (hpreconds : ∀ p ∈ preconds, p.holds σ) :
    ∃ cs', MidenLean.execInstruction cs .u32AssertW = some cs' ∧ ss'.models cs' σ rest := by
  obtain ⟨hstack, hmem, hframes, hadv⟩ := hmodels
  simp only [execInstruction] at hexec
  match hstk : ss.stack with
  | [] | [_] | [_, _] | [_, _, _] => simp [hstk] at hexec
  | a :: b :: c :: d :: tail =>
    simp only [hstk] at hexec
    obtain ⟨rfl, rfl⟩ := Prod.mk.inj (Option.some.inj hexec)
    rw [hstk, List.map_cons, List.map_cons, List.map_cons, List.map_cons] at hstack
    have ha : (a.eval σ).isU32 = true :=
      hpreconds (.isU32 a) (by simp)
    have hb : (b.eval σ).isU32 = true :=
      hpreconds (.isU32 b) (by simp)
    have hc : (c.eval σ).isU32 = true :=
      hpreconds (.isU32 c) (by simp)
    have hd : (d.eval σ).isU32 = true :=
      hpreconds (.isU32 d) (by simp)
    have hguard : ((a.eval σ).isU32 && (b.eval σ).isU32 &&
                   (c.eval σ).isU32 && (d.eval σ).isU32) = true := by
      rw [ha, hb, hc, hd]; rfl
    refine ⟨cs, ?_, ?_⟩
    · change execU32AssertW cs = _
      unfold execU32AssertW
      rw [hstack]; simp [hguard]
    · exact ⟨by simp only [hstk, hstack, List.map_cons], hmem, hframes, hadv⟩

-- U32 shift/rotate with an immediate (isU32 precondition + static bound)

theorem execInstruction_sound_u32ShlImm
    (n : Nat) (ss : State) (cs : Concrete.State)
    (σ : Assignment) (rest : List Felt)
    (ss' : State) (preconds : List Precondition)
    (hmodels : ss.models cs σ rest)
    (hexec : execInstruction ss (.u32ShlImm n) = some (ss', preconds))
    (hpreconds : ∀ p ∈ preconds, p.holds σ) :
    ∃ cs', MidenLean.execInstruction cs (.u32ShlImm n) = some cs' ∧ ss'.models cs' σ rest := by
  obtain ⟨hstack, hmem, hframes, hadv⟩ := hmodels
  simp only [execInstruction] at hexec
  by_cases hn : n ≤ 31
  · simp only [hn, ite_true] at hexec
    match hstk : ss.stack with
    | [] => simp [hstk] at hexec
    | a :: tail =>
      simp only [hstk] at hexec
      obtain ⟨rfl, rfl⟩ := Prod.mk.inj (Option.some.inj hexec)
      rw [hstk, List.map_cons, List.cons_append] at hstack
      have ha : (a.eval σ).isU32 = true :=
        hpreconds (.isU32 a) (by simp)
      have hnguard : ¬(n > 31) := by omega
      have hnval : (Felt.ofNat n).val = n := feltOfNat_val_small n hn
      refine ⟨cs.withStack (Felt.ofNat (((a.eval σ).val * 2 ^ n) % u32Max) ::
                            tail.map (Expr.eval σ) ++ rest), ?_, ?_⟩
      · change execU32ShlImm n cs = _
        unfold execU32ShlImm
        rw [hstack]; simp [ha, hnguard, Concrete.State.withStack]
      · exact ⟨by simp only [Concrete.State.withStack, List.map_cons, Expr.eval,
            List.cons_append, hnval], hmem, hframes, hadv⟩
  · simp [hn] at hexec


theorem execInstruction_sound_u32ShrImm
    (n : Nat) (ss : State) (cs : Concrete.State)
    (σ : Assignment) (rest : List Felt)
    (ss' : State) (preconds : List Precondition)
    (hmodels : ss.models cs σ rest)
    (hexec : execInstruction ss (.u32ShrImm n) = some (ss', preconds))
    (hpreconds : ∀ p ∈ preconds, p.holds σ) :
    ∃ cs', MidenLean.execInstruction cs (.u32ShrImm n) = some cs' ∧ ss'.models cs' σ rest := by
  obtain ⟨hstack, hmem, hframes, hadv⟩ := hmodels
  simp only [execInstruction] at hexec
  by_cases hn : n ≤ 31
  · simp only [hn, ite_true] at hexec
    match hstk : ss.stack with
    | [] => simp [hstk] at hexec
    | a :: tail =>
      simp only [hstk] at hexec
      obtain ⟨rfl, rfl⟩ := Prod.mk.inj (Option.some.inj hexec)
      rw [hstk, List.map_cons, List.cons_append] at hstack
      have ha : (a.eval σ).isU32 = true :=
        hpreconds (.isU32 a) (by simp)
      have hnguard : ¬(n > 31) := by omega
      have hnval : (Felt.ofNat n).val = n := feltOfNat_val_small n hn
      refine ⟨cs.withStack (Felt.ofNat ((a.eval σ).val / 2 ^ n) ::
                            tail.map (Expr.eval σ) ++ rest), ?_, ?_⟩
      · change execU32ShrImm n cs = _
        unfold execU32ShrImm
        rw [hstack]; simp [ha, hnguard, Concrete.State.withStack]
      · exact ⟨by simp only [Concrete.State.withStack, List.map_cons, Expr.eval,
            List.cons_append, hnval], hmem, hframes, hadv⟩
  · simp [hn] at hexec


theorem execInstruction_sound_u32RotlImm
    (n : Nat) (ss : State) (cs : Concrete.State)
    (σ : Assignment) (rest : List Felt)
    (ss' : State) (preconds : List Precondition)
    (hmodels : ss.models cs σ rest)
    (hexec : execInstruction ss (.u32RotlImm n) = some (ss', preconds))
    (hpreconds : ∀ p ∈ preconds, p.holds σ) :
    ∃ cs', MidenLean.execInstruction cs (.u32RotlImm n) = some cs' ∧ ss'.models cs' σ rest := by
  obtain ⟨hstack, hmem, hframes, hadv⟩ := hmodels
  simp only [execInstruction] at hexec
  by_cases hn : n ≤ 31
  · simp only [hn, ite_true] at hexec
    match hstk : ss.stack with
    | [] => simp [hstk] at hexec
    | a :: tail =>
      simp only [hstk] at hexec
      obtain ⟨rfl, rfl⟩ := Prod.mk.inj (Option.some.inj hexec)
      rw [hstk, List.map_cons, List.cons_append] at hstack
      have ha : (a.eval σ).isU32 = true :=
        hpreconds (.isU32 a) (by simp)
      have hnguard : ¬(n > 31) := by omega
      have hnval : (Felt.ofNat n).val = n := feltOfNat_val_small n hn
      refine ⟨cs.withStack (Felt.ofNat (u32RotateLeft (a.eval σ).val n) ::
                            tail.map (Expr.eval σ) ++ rest), ?_, ?_⟩
      · change execU32RotlImm n cs = _
        unfold execU32RotlImm
        rw [hstack]; simp [ha, hnguard, Concrete.State.withStack]
      · exact ⟨by simp only [Concrete.State.withStack, List.map_cons, Expr.eval,
            List.cons_append, hnval], hmem, hframes, hadv⟩
  · simp [hn] at hexec


theorem execInstruction_sound_u32RotrImm
    (n : Nat) (ss : State) (cs : Concrete.State)
    (σ : Assignment) (rest : List Felt)
    (ss' : State) (preconds : List Precondition)
    (hmodels : ss.models cs σ rest)
    (hexec : execInstruction ss (.u32RotrImm n) = some (ss', preconds))
    (hpreconds : ∀ p ∈ preconds, p.holds σ) :
    ∃ cs', MidenLean.execInstruction cs (.u32RotrImm n) = some cs' ∧ ss'.models cs' σ rest := by
  obtain ⟨hstack, hmem, hframes, hadv⟩ := hmodels
  simp only [execInstruction] at hexec
  by_cases hn : n ≤ 31
  · simp only [hn, ite_true] at hexec
    match hstk : ss.stack with
    | [] => simp [hstk] at hexec
    | a :: tail =>
      simp only [hstk] at hexec
      obtain ⟨rfl, rfl⟩ := Prod.mk.inj (Option.some.inj hexec)
      rw [hstk, List.map_cons, List.cons_append] at hstack
      have ha : (a.eval σ).isU32 = true :=
        hpreconds (.isU32 a) (by simp)
      have hnguard : ¬(n > 31) := by omega
      have hnval : (Felt.ofNat n).val = n := feltOfNat_val_small n hn
      refine ⟨cs.withStack (Felt.ofNat (u32RotateRight (a.eval σ).val n) ::
                            tail.map (Expr.eval σ) ++ rest), ?_, ?_⟩
      · change execU32RotrImm n cs = _
        unfold execU32RotrImm
        rw [hstack]; simp [ha, hnguard, Concrete.State.withStack]
      · exact ⟨by simp only [Concrete.State.withStack, List.map_cons, Expr.eval,
            List.cons_append, hnval], hmem, hframes, hadv⟩
  · simp [hn] at hexec

-- Word and indexed stack ops (multi-element access via getElem?)

theorem execInstruction_sound_dupw
    (n : Fin 4) (ss : State) (cs : Concrete.State)
    (σ : Assignment) (rest : List Felt)
    (ss' : State) (preconds : List Precondition)
    (hmodels : ss.models cs σ rest)
    (hexec : execInstruction ss (.dupw n) = some (ss', preconds))
    (hpreconds : ∀ p ∈ preconds, p.holds σ) :
    ∃ cs', MidenLean.execInstruction cs (.dupw n) = some cs' ∧ ss'.models cs' σ rest := by
  obtain ⟨hstack, hmem, hframes, hadv⟩ := hmodels
  simp only [execInstruction] at hexec
  set base := n.val * 4 with hbase_def
  match hga : ss.stack[base]?, hgb : ss.stack[base + 1]?,
        hgc : ss.stack[base + 2]?, hgd : ss.stack[base + 3]? with
  | some a, some b, some c, some d =>
    simp only [hga, hgb, hgc, hgd] at hexec
    obtain ⟨rfl, rfl⟩ := Prod.mk.inj (Option.some.inj hexec)
    have hna : base < ss.stack.length := getElem?_some_lt _ _ _ hga
    have hnb : base + 1 < ss.stack.length := getElem?_some_lt _ _ _ hgb
    have hnc : base + 2 < ss.stack.length := getElem?_some_lt _ _ _ hgc
    have hnd : base + 3 < ss.stack.length := getElem?_some_lt _ _ _ hgd
    have hva : ss.stack[base] = a := getElem_of_getElem?_some _ _ _ hga
    have hvb : ss.stack[base + 1] = b := getElem_of_getElem?_some _ _ _ hgb
    have hvc : ss.stack[base + 2] = c := getElem_of_getElem?_some _ _ _ hgc
    have hvd : ss.stack[base + 3] = d := getElem_of_getElem?_some _ _ _ hgd
    refine ⟨cs.withStack (a.eval σ :: b.eval σ :: c.eval σ :: d.eval σ :: cs.stack), ?_, ?_⟩
    · simp only [MidenLean.execInstruction, execDupw, hstack]
      rw [getElem?_map_append_left (Expr.eval σ) ss.stack rest base hna,
          getElem?_map_append_left (Expr.eval σ) ss.stack rest (base + 1) hnb,
          getElem?_map_append_left (Expr.eval σ) ss.stack rest (base + 2) hnc,
          getElem?_map_append_left (Expr.eval σ) ss.stack rest (base + 3) hnd]
      rw [hva, hvb, hvc, hvd]
    · exact ⟨by simp only [Concrete.State.withStack, List.map_cons, hstack]; rfl, hmem, hframes, hadv⟩
  | _, _, _, _ =>
    simp only [hga, hgb, hgc, hgd] at hexec
    split at hexec
    next a' b' c' d' =>
      obtain ⟨rfl, rfl⟩ := hexec
      have hna : base < ss.stack.length := getElem?_some_lt _ _ _ hga
      have hnb : base + 1 < ss.stack.length := getElem?_some_lt _ _ _ hgb
      have hnc : base + 2 < ss.stack.length := getElem?_some_lt _ _ _ hgc
      have hnd : base + 3 < ss.stack.length := getElem?_some_lt _ _ _ hgd
      have hva : ss.stack[base] = a' := getElem_of_getElem?_some _ _ _ hga
      have hvb : ss.stack[base + 1] = b' := getElem_of_getElem?_some _ _ _ hgb
      have hvc : ss.stack[base + 2] = c' := getElem_of_getElem?_some _ _ _ hgc
      have hvd : ss.stack[base + 3] = d' := getElem_of_getElem?_some _ _ _ hgd
      refine ⟨cs.withStack (a'.eval σ :: b'.eval σ :: c'.eval σ :: d'.eval σ :: cs.stack), ?_, ?_⟩
      · simp only [MidenLean.execInstruction, execDupw, hstack]
        rw [getElem?_map_append_left (Expr.eval σ) ss.stack rest base hna,
            getElem?_map_append_left (Expr.eval σ) ss.stack rest (base + 1) hnb,
            getElem?_map_append_left (Expr.eval σ) ss.stack rest (base + 2) hnc,
            getElem?_map_append_left (Expr.eval σ) ss.stack rest (base + 3) hnd]
        rw [hva, hvb, hvc, hvd]
      · exact ⟨by simp only [Concrete.State.withStack, List.map_cons, hstack]; rfl, hmem, hframes, hadv⟩
    next h =>
      exact absurd hexec (by simp)

set_option maxHeartbeats 1600000 in

theorem execInstruction_sound_swapw
    (n : Fin 4) (ss : State) (cs : Concrete.State)
    (σ : Assignment) (rest : List Felt)
    (ss' : State) (preconds : List Precondition)
    (hmodels : ss.models cs σ rest)
    (hexec : execInstruction ss (.swapw n) = some (ss', preconds))
    (hpreconds : ∀ p ∈ preconds, p.holds σ) :
    ∃ cs', MidenLean.execInstruction cs (.swapw n) = some cs' ∧ ss'.models cs' σ rest := by
  obtain ⟨hstack, hmem, hframes, hadv⟩ := hmodels
  -- Restate the `cons`-pattern definition in the index/`List.set` form that the
  -- concrete `execSwapw` uses (the two agree for every `n` and stack shape).
  rw [execInstruction_swapw_setForm] at hexec
  -- Split on the if (n.val == 0) condition inside hexec
  split at hexec
  · -- n = 0: identity case
    rename_i h0
    obtain ⟨rfl, rfl⟩ := Prod.mk.inj (Option.some.inj hexec)
    exact ⟨cs,
      by simp [MidenLean.execInstruction, execSwapw, h0],
      hstack, hmem, hframes, hadv⟩
  · -- n ≠ 0: 8-element swap
    -- Split on the 8-way match inside hexec
    split at hexec
    · -- all 8 getElem? are some (a0..a3 at 0..3, b0..b3 at n*4..n*4+3)
      rename_i h0 _ _ _ _ _ _ _ _ a0 a1 a2 a3 b0 b1 b2 b3 hg0 hg1 hg2 hg3 hgb0 hgb1 hgb2 hgb3
      obtain ⟨rfl, rfl⟩ := Prod.mk.inj (Option.some.inj hexec)
      have h0lt : 0 < ss.stack.length := getElem?_some_lt _ _ _ hg0
      have h1lt : 1 < ss.stack.length := getElem?_some_lt _ _ _ hg1
      have h2lt : 2 < ss.stack.length := getElem?_some_lt _ _ _ hg2
      have h3lt : 3 < ss.stack.length := getElem?_some_lt _ _ _ hg3
      have hb0lt : n.val * 4 < ss.stack.length := getElem?_some_lt _ _ _ hgb0
      have hb1lt : n.val * 4 + 1 < ss.stack.length := getElem?_some_lt _ _ _ hgb1
      have hb2lt : n.val * 4 + 2 < ss.stack.length := getElem?_some_lt _ _ _ hgb2
      have hb3lt : n.val * 4 + 3 < ss.stack.length := getElem?_some_lt _ _ _ hgb3
      have hv0 : ss.stack[0] = a0 := getElem_of_getElem?_some _ _ _ hg0
      have hv1 : ss.stack[1] = a1 := getElem_of_getElem?_some _ _ _ hg1
      have hv2 : ss.stack[2] = a2 := getElem_of_getElem?_some _ _ _ hg2
      have hv3 : ss.stack[3] = a3 := getElem_of_getElem?_some _ _ _ hg3
      have hvb0 : ss.stack[n.val * 4] = b0 := getElem_of_getElem?_some _ _ _ hgb0
      have hvb1 : ss.stack[n.val * 4 + 1] = b1 := getElem_of_getElem?_some _ _ _ hgb1
      have hvb2 : ss.stack[n.val * 4 + 2] = b2 := getElem_of_getElem?_some _ _ _ hgb2
      have hvb3 : ss.stack[n.val * 4 + 3] = b3 := getElem_of_getElem?_some _ _ _ hgb3
      refine ⟨cs.withStack ((cs.stack.set 0 (b0.eval σ) |>.set 1 (b1.eval σ) |>.set 2 (b2.eval σ)
                             |>.set 3 (b3.eval σ) |>.set (n.val * 4) (a0.eval σ)
                             |>.set (n.val * 4 + 1) (a1.eval σ)
                             |>.set (n.val * 4 + 2) (a2.eval σ)
                             |>.set (n.val * 4 + 3) (a3.eval σ))), ?_, ?_⟩
      · simp only [MidenLean.execInstruction, execSwapw]
        split
        · -- n == 0 case (contradicts h0)
          rename_i h0eq; exact absurd h0eq h0
        · -- n ≠ 0 case
          rw [hstack,
              getElem?_map_append_left (Expr.eval σ) ss.stack rest 0 h0lt,
              getElem?_map_append_left (Expr.eval σ) ss.stack rest 1 h1lt,
              getElem?_map_append_left (Expr.eval σ) ss.stack rest 2 h2lt,
              getElem?_map_append_left (Expr.eval σ) ss.stack rest 3 h3lt,
              getElem?_map_append_left (Expr.eval σ) ss.stack rest (n.val * 4) hb0lt,
              getElem?_map_append_left (Expr.eval σ) ss.stack rest (n.val * 4 + 1) hb1lt,
              getElem?_map_append_left (Expr.eval σ) ss.stack rest (n.val * 4 + 2) hb2lt,
              getElem?_map_append_left (Expr.eval σ) ss.stack rest (n.val * 4 + 3) hb3lt]
          rw [hv0, hv1, hv2, hv3, hvb0, hvb1, hvb2, hvb3]
      · refine ⟨?_, hmem, hframes, hadv⟩
        unfold Concrete.State.withStack
        rw [hstack,
            set_map_append_left _ _ _ (n.val * 4 + 3) a3 (by simp [List.length_set]; exact hb3lt),
            set_map_append_left _ _ _ (n.val * 4 + 2) a2 (by simp [List.length_set]; exact hb2lt),
            set_map_append_left _ _ _ (n.val * 4 + 1) a1 (by simp [List.length_set]; exact hb1lt),
            set_map_append_left _ _ _ (n.val * 4) a0 (by simp [List.length_set]; exact hb0lt),
            set_map_append_left _ _ _ 3 b3 (by simp [List.length_set]; exact h3lt),
            set_map_append_left _ _ _ 2 b2 (by simp [List.length_set]; exact h2lt),
            set_map_append_left _ _ _ 1 b1 (by simp [List.length_set]; exact h1lt),
            set_map_append_left _ _ _ 0 b0 h0lt]
    · -- not all some: contradiction
      exact absurd hexec (by simp)

set_option maxHeartbeats 800000 in

theorem execInstruction_sound_movupw
    (n : Nat) (ss : State) (cs : Concrete.State)
    (σ : Assignment) (rest : List Felt)
    (ss' : State) (preconds : List Precondition)
    (hmodels : ss.models cs σ rest)
    (hexec : execInstruction ss (.movupw n) = some (ss', preconds))
    (hpreconds : ∀ p ∈ preconds, p.holds σ) :
    ∃ cs', MidenLean.execInstruction cs (.movupw n) = some cs' ∧ ss'.models cs' σ rest := by
  obtain ⟨hstack, hmem, hframes, hadv⟩ := hmodels
  simp only [execInstruction] at hexec
  by_cases hrange : 2 ≤ n ∧ n ≤ 3
  · have htrue : (decide (2 ≤ n) && decide (n ≤ 3)) = true := by
      simp only [Bool.and_eq_true, decide_eq_true_eq]; exact hrange
    simp only [htrue, ite_true] at hexec
    set base := n * 4 with hbase_def
    by_cases hlen : ss.stack.length < base + 4
    · simp [hlen] at hexec
    · push_neg at hlen
      rw [if_neg (by omega)] at hexec
      obtain ⟨rfl, rfl⟩ := Prod.mk.inj (Option.some.inj hexec)
      have hle : base + 4 ≤ ss.stack.length := hlen
      refine ⟨cs.withStack (((ss.stack.map (Expr.eval σ)).drop base).take 4 ++
                              (ss.stack.map (Expr.eval σ)).take base ++
                              (ss.stack.map (Expr.eval σ)).drop (base + 4) ++ rest), ?_, ?_⟩
      · change execMovupw n cs = _
        unfold execMovupw
        have hnlt2 : ¬(n < 2) := by omega
        have hngt3 : ¬(n > 3) := by omega
        have hguard : (n < 2 || n > 3) = false := by
          simp [hnlt2, hngt3]
        simp only [hguard]
        rw [hstack]
        have hle' : base + 4 ≤ (ss.stack.map (Expr.eval σ) ++ rest).length := by simp; omega
        simp only [Concrete.State.withStack]
        rw [List.take_append_of_le_length (by simp; omega),
            List.drop_append_of_le_length (by simp; omega)]
        rw [List.take_append_of_le_length (by simp [List.length_drop]; omega),
            List.drop_append_of_le_length (by simp; omega)]
        simp only [List.append_assoc, hbase_def]
        simp; omega
      · exact ⟨by simp only [Concrete.State.withStack,
            List.map_append, List.map_take, List.map_drop, List.append_assoc], hmem, hframes, hadv⟩
  · have hfalse : (decide (2 ≤ n) && decide (n ≤ 3)) = false := by
      simp only [Bool.and_eq_false_iff, decide_eq_false_iff_not]; omega
    simp [hfalse] at hexec

set_option maxHeartbeats 800000 in

theorem execInstruction_sound_movdnw
    (n : Nat) (ss : State) (cs : Concrete.State)
    (σ : Assignment) (rest : List Felt)
    (ss' : State) (preconds : List Precondition)
    (hmodels : ss.models cs σ rest)
    (hexec : execInstruction ss (.movdnw n) = some (ss', preconds))
    (hpreconds : ∀ p ∈ preconds, p.holds σ) :
    ∃ cs', MidenLean.execInstruction cs (.movdnw n) = some cs' ∧ ss'.models cs' σ rest := by
  obtain ⟨hstack, hmem, hframes, hadv⟩ := hmodels
  simp only [execInstruction] at hexec
  by_cases hrange : 2 ≤ n ∧ n ≤ 3
  · have htrue : (decide (2 ≤ n) && decide (n ≤ 3)) = true := by
      simp only [Bool.and_eq_true, decide_eq_true_eq]; exact hrange
    simp only [htrue, ite_true] at hexec
    by_cases hlen : ss.stack.length < (n + 1) * 4
    · simp [hlen] at hexec
    · push_neg at hlen
      rw [if_neg (by omega)] at hexec
      obtain ⟨rfl, rfl⟩ := Prod.mk.inj (Option.some.inj hexec)
      have hle : (n + 1) * 4 ≤ ss.stack.length := hlen
      refine ⟨cs.withStack (((ss.stack.map (Expr.eval σ)).drop 4).take (n * 4) ++
                              (ss.stack.map (Expr.eval σ)).take 4 ++
                              ((ss.stack.map (Expr.eval σ)).drop 4).drop (n * 4) ++ rest), ?_, ?_⟩
      · change execMovdnw n cs = _
        unfold execMovdnw
        have hnlt2 : ¬(n < 2) := by omega
        have hngt3 : ¬(n > 3) := by omega
        have hguard : (n < 2 || n > 3) = false := by
          simp [hnlt2, hngt3]
        simp only [hguard]
        rw [hstack]
        have hle' : (n + 1) * 4 ≤ (ss.stack.map (Expr.eval σ) ++ rest).length := by simp; omega
        simp only [Concrete.State.withStack]
        rw [List.take_append_of_le_length (by simp; omega),
            List.drop_append_of_le_length (by simp; omega)]
        rw [List.take_append_of_le_length (by simp [List.length_drop]; omega),
            List.drop_append_of_le_length (by simp [List.length_drop]; omega)]
        simp [List.append_assoc]
        omega
      · exact ⟨by simp only [Concrete.State.withStack,
            List.map_append, List.map_take, List.map_drop, List.append_assoc], hmem, hframes, hadv⟩
  · have hfalse : (decide (2 ≤ n) && decide (n ≤ 3)) = false := by
      simp only [Bool.and_eq_false_iff, decide_eq_false_iff_not]; omega
    simp [hfalse] at hexec

-- Conditional swap/drop ops (isBool precondition)


theorem execInstruction_sound_cswap
    (ss : State) (cs : Concrete.State)
    (σ : Assignment) (rest : List Felt)
    (ss' : State) (preconds : List Precondition)
    (hmodels : ss.models cs σ rest)
    (hexec : execInstruction ss .cswap = some (ss', preconds))
    (hpreconds : ∀ p ∈ preconds, p.holds σ) :
    ∃ cs', MidenLean.execInstruction cs .cswap = some cs' ∧ ss'.models cs' σ rest := by
  obtain ⟨hstack, hmem, hframes, hadv⟩ := hmodels
  simp only [execInstruction] at hexec
  -- Use split on the inner match (ss.stack) in hexec
  split at hexec
  · -- Matching case: c :: b :: a :: rest
    rename_i c b a tail heq_stk
    obtain ⟨rfl, rfl⟩ := Prod.mk.inj (Option.some.inj hexec)
    rw [heq_stk, List.map_cons, List.map_cons, List.map_cons] at hstack
    have hbool : (c.eval σ) = 0 ∨ (c.eval σ) = 1 :=
      hpreconds (.isBool c) (by simp)
    rcases hbool with hc0 | hc1
    · -- c.eval σ = 0: concrete takes the "c.val == 0" branch, symbolic ite takes else
      refine ⟨cs.withStack (b.eval σ :: a.eval σ :: tail.map (Expr.eval σ) ++ rest), ?_, ?_⟩
      · change execCswap cs = _
        unfold execCswap
        rw [hstack, hc0]
        simp [ZMod.val_zero, Concrete.State.withStack]
      · refine ⟨?_, hmem, hframes, hadv⟩
        simp [Concrete.State.withStack, Expr.eval, hc0]
    · -- c.eval σ = 1: concrete takes the "c.val == 1" branch, symbolic ite takes then
      refine ⟨cs.withStack (a.eval σ :: b.eval σ :: tail.map (Expr.eval σ) ++ rest), ?_, ?_⟩
      · change execCswap cs = _
        unfold execCswap
        rw [hstack, hc1]
        simp [ZMod.val_one, Concrete.State.withStack]
      · refine ⟨?_, hmem, hframes, hadv⟩
        simp [Concrete.State.withStack, Expr.eval, hc1, ZMod.val_one]
  · -- Wildcard case: hexec : none = some ... is contradictory
    exact absurd hexec (by simp)


theorem execInstruction_sound_cdrop
    (ss : State) (cs : Concrete.State)
    (σ : Assignment) (rest : List Felt)
    (ss' : State) (preconds : List Precondition)
    (hmodels : ss.models cs σ rest)
    (hexec : execInstruction ss .cdrop = some (ss', preconds))
    (hpreconds : ∀ p ∈ preconds, p.holds σ) :
    ∃ cs', MidenLean.execInstruction cs .cdrop = some cs' ∧ ss'.models cs' σ rest := by
  obtain ⟨hstack, hmem, hframes, hadv⟩ := hmodels
  simp only [execInstruction] at hexec
  split at hexec
  · -- Matching case: c :: b :: a :: rest
    rename_i c b a tail heq_stk
    obtain ⟨rfl, rfl⟩ := Prod.mk.inj (Option.some.inj hexec)
    rw [heq_stk, List.map_cons, List.map_cons, List.map_cons] at hstack
    have hbool : (c.eval σ) = 0 ∨ (c.eval σ) = 1 :=
      hpreconds (.isBool c) (by simp)
    rcases hbool with hc0 | hc1
    · -- c.eval σ = 0: concrete drops b, keeps a; symbolic ite c b a → a (else branch)
      refine ⟨cs.withStack (a.eval σ :: tail.map (Expr.eval σ) ++ rest), ?_, ?_⟩
      · change execCdrop cs = _
        unfold execCdrop
        rw [hstack, hc0]
        simp [ZMod.val_zero, Concrete.State.withStack]
      · refine ⟨?_, hmem, hframes, hadv⟩
        simp [Concrete.State.withStack, Expr.eval, hc0]
    · -- c.eval σ = 1: concrete drops a, keeps b; symbolic ite c b a → b (then branch)
      refine ⟨cs.withStack (b.eval σ :: tail.map (Expr.eval σ) ++ rest), ?_, ?_⟩
      · change execCdrop cs = _
        unfold execCdrop
        rw [hstack, hc1]
        simp [ZMod.val_one, Concrete.State.withStack]
      · refine ⟨?_, hmem, hframes, hadv⟩
        simp [Concrete.State.withStack, Expr.eval, hc1, ZMod.val_one]
  · -- Wildcard case
    exact absurd hexec (by simp)

set_option maxHeartbeats 800000 in

theorem execInstruction_sound_cswapw
    (ss : State) (cs : Concrete.State)
    (σ : Assignment) (rest : List Felt)
    (ss' : State) (preconds : List Precondition)
    (hmodels : ss.models cs σ rest)
    (hexec : execInstruction ss .cswapw = some (ss', preconds))
    (hpreconds : ∀ p ∈ preconds, p.holds σ) :
    ∃ cs', MidenLean.execInstruction cs .cswapw = some cs' ∧ ss'.models cs' σ rest := by
  obtain ⟨hstack, hmem, hframes, hadv⟩ := hmodels
  simp only [execInstruction] at hexec
  -- The symbolic executor's cswapw case has a let binding; use split to handle the inner match
  split at hexec
  swap
  · -- Wildcard case: hexec : none = some ... is contradictory
    exact absurd hexec (by simp)
  · -- Matching case: 9-element pattern
    rename_i c b0 b1 b2 b3 a0 a1 a2 a3 tail heq_stk
    obtain ⟨rfl, rfl⟩ := Prod.mk.inj (Option.some.inj hexec)
    rw [heq_stk, List.map_cons, List.map_cons, List.map_cons, List.map_cons, List.map_cons,
        List.map_cons, List.map_cons, List.map_cons, List.map_cons] at hstack
    have hbool : (c.eval σ) = 0 ∨ (c.eval σ) = 1 :=
      hpreconds (.isBool c) (by simp)
    rcases hbool with hc0 | hc1
    · -- c.eval σ = 0: concrete keeps b0..b3 :: a0..a3, symbolic ite takes else
      refine ⟨cs.withStack (b0.eval σ :: b1.eval σ :: b2.eval σ :: b3.eval σ ::
                             a0.eval σ :: a1.eval σ :: a2.eval σ :: a3.eval σ ::
                             tail.map (Expr.eval σ) ++ rest), ?_, ?_⟩
      · change execCswapw cs = _
        unfold execCswapw
        rw [hstack, hc0]
        simp [ZMod.val_zero, Concrete.State.withStack]
      · refine ⟨?_, hmem, hframes, hadv⟩
        simp [Concrete.State.withStack, Expr.eval, hc0]
    · -- c.eval σ = 1: concrete swaps to a0..a3 :: b0..b3, symbolic ite takes then
      refine ⟨cs.withStack (a0.eval σ :: a1.eval σ :: a2.eval σ :: a3.eval σ ::
                             b0.eval σ :: b1.eval σ :: b2.eval σ :: b3.eval σ ::
                             tail.map (Expr.eval σ) ++ rest), ?_, ?_⟩
      · change execCswapw cs = _
        unfold execCswapw
        rw [hstack, hc1]
        simp [ZMod.val_one, Concrete.State.withStack]
      · refine ⟨?_, hmem, hframes, hadv⟩
        simp [Concrete.State.withStack, Expr.eval, hc1, ZMod.val_one]

set_option maxHeartbeats 800000 in

theorem execInstruction_sound_cdropw
    (ss : State) (cs : Concrete.State)
    (σ : Assignment) (rest : List Felt)
    (ss' : State) (preconds : List Precondition)
    (hmodels : ss.models cs σ rest)
    (hexec : execInstruction ss .cdropw = some (ss', preconds))
    (hpreconds : ∀ p ∈ preconds, p.holds σ) :
    ∃ cs', MidenLean.execInstruction cs .cdropw = some cs' ∧ ss'.models cs' σ rest := by
  obtain ⟨hstack, hmem, hframes, hadv⟩ := hmodels
  simp only [execInstruction] at hexec
  -- The symbolic executor's cdropw case has a let binding; use split to handle the inner match
  split at hexec
  swap
  · -- Wildcard case: hexec : none = some ... is contradictory
    exact absurd hexec (by simp)
  · -- Matching case: 9-element pattern
    rename_i c b0 b1 b2 b3 a0 a1 a2 a3 tail heq_stk
    obtain ⟨rfl, rfl⟩ := Prod.mk.inj (Option.some.inj hexec)
    rw [heq_stk, List.map_cons, List.map_cons, List.map_cons, List.map_cons, List.map_cons,
        List.map_cons, List.map_cons, List.map_cons, List.map_cons] at hstack
    have hbool : (c.eval σ) = 0 ∨ (c.eval σ) = 1 :=
      hpreconds (.isBool c) (by simp)
    rcases hbool with hc0 | hc1
    · -- c.eval σ = 0: concrete keeps a0..a3, symbolic ite takes else
      refine ⟨cs.withStack (a0.eval σ :: a1.eval σ :: a2.eval σ :: a3.eval σ ::
                             tail.map (Expr.eval σ) ++ rest), ?_, ?_⟩
      · change execCdropw cs = _
        unfold execCdropw
        rw [hstack, hc0]
        simp [ZMod.val_zero, Concrete.State.withStack]
      · refine ⟨?_, hmem, hframes, hadv⟩
        simp [Concrete.State.withStack, Expr.eval, hc0]
    · -- c.eval σ = 1: concrete keeps b0..b3, symbolic ite takes then
      refine ⟨cs.withStack (b0.eval σ :: b1.eval σ :: b2.eval σ :: b3.eval σ ::
                             tail.map (Expr.eval σ) ++ rest), ?_, ?_⟩
      · change execCdropw cs = _
        unfold execCdropw
        rw [hstack, hc1]
        simp [ZMod.val_one, Concrete.State.withStack]
      · refine ⟨?_, hmem, hframes, hadv⟩
        simp [Concrete.State.withStack, Expr.eval, hc1, ZMod.val_one]


end MidenLean.Symbolic
